# -*- coding: utf-8 -*-
"""Manobras do Mestre da Batalha (cap. 3, p. 134-135)."""
import json, os
D = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'dados')
def f(p): return {"capitulo": 3, "pagina_livro": p, "pagina_pdf": p + 4}
DS = "dado:superioridade"
CD = ["8", "mod:FOR_ou_DES", "prof"]   # CD das manobras (p. 133)
def m(id_, nome, pag, custo, desc, efeitos, **kw):
    d = {"id": id_, "nome": nome, "fonte": f(pag), "custo": custo,
         "consome_dado_de_superioridade": True, "descricao_curta": desc, "efeitos": efeitos}
    d.update(kw); return d

M = [
 m("aparar", "Aparar", 134, "reacao",
   "Reação ao sofrer dano de ataque corpo a corpo: reduz o dano no resultado do Dado de Superioridade mais seu modificador de Força ou Destreza.",
   [{"tipo": "reducao_de_dano", "formula": [DS, "mod:FOR_ou_DES"], "tipos_de_dano": ["todos"],
     "gatilho": "sofrer_dano_de_ataque_corpo_a_corpo"}]),
 m("ataque_ameacador", "Ataque Ameaçador", 134, "no_acerto",
   "Soma o Dado de Superioridade ao dano; o alvo faz salvaguarda de Sabedoria ou fica Amedrontado até o fim do seu próximo turno.",
   [{"tipo": "dano", "formula_dado": DS, "modo": "dano_adicional", "tipo_dano": "mesmo_do_ataque"},
    {"tipo": "conceder_condicao", "condicao_id": "amedrontado", "beneficiario": "alvo",
     "salvaguarda": {"atributo": "SAB", "cd": CD}, "duracao": "ate_o_fim_do_seu_proximo_turno"}]),
 m("ataque_de_varredura", "Ataque de Varredura", 134, "no_acerto",
   "Ao acertar corpo a corpo, escolhe outra criatura a até 1,5 m do alvo e ao seu alcance: se a jogada original a atingiria, ela sofre dano igual ao Dado de Superioridade, do mesmo tipo.",
   [{"tipo": "dano", "formula_dado": DS, "tipo_dano": "mesmo_do_ataque", "alvo": "segunda_criatura",
     "condicao": {"todas": ["segunda_criatura_a_ate_1_5m_do_alvo", "jogada_original_atinge_a_segunda"]}}]),
 m("ataque_estendido", "Ataque Estendido", 134, "acao_bonus",
   "Ação Bônus para executar Correr; se mover ao menos 1,5 m em linha reta antes de um ataque corpo a corpo da ação Atacar neste turno, soma o Dado de Superioridade ao dano.",
   [{"tipo": "conceder_acao", "id": "manobra_correr", "custo": "acao_bonus", "acoes": ["correr"]},
    {"tipo": "dano", "formula_dado": DS, "modo": "dano_adicional",
     "condicao": {"todas": ["moveu_1_5m_em_linha_reta_antes_do_ataque"]}}]),
 m("ataque_para_distrair", "Ataque para Distrair", 134, "no_acerto",
   "Soma o Dado de Superioridade ao dano; a próxima jogada de ataque contra o alvo por outro atacante tem Vantagem, se for antes do início do seu próximo turno.",
   [{"tipo": "dano", "formula_dado": DS, "modo": "dano_adicional", "tipo_dano": "mesmo_do_ataque"},
    {"tipo": "vantagem", "alvo": "jogada_de_ataque", "modo": "vantagem", "beneficiario": "outro_atacante",
     "duracao": "ate_inicio_do_seu_proximo_turno"}]),
 m("ataque_preciso", "Ataque Preciso", 134, "no_erro",
   "Ao errar, soma o Dado de Superioridade à jogada de ataque, podendo transformá-la em acerto.",
   [{"tipo": "modificador", "alvo": "jogada_de_ataque", "valor": [DS], "empilha": "soma",
     "gatilho": "erro", "momento": "apos_a_jogada"}]),
 m("ataque_provocante", "Ataque Provocante", 135, "no_acerto",
   "Soma o Dado de Superioridade ao dano; o alvo faz salvaguarda de Sabedoria ou tem Desvantagem em ataques contra qualquer alvo que não seja você até o fim do seu próximo turno.",
   [{"tipo": "dano", "formula_dado": DS, "modo": "dano_adicional", "tipo_dano": "mesmo_do_ataque"},
    {"tipo": "vantagem", "alvo": "jogada_de_ataque", "modo": "desvantagem", "beneficiario": "alvo",
     "salvaguarda": {"atributo": "SAB", "cd": CD},
     "condicao": {"nao": "alvo_do_ataque_e_voce"}, "duracao": "ate_o_fim_do_seu_proximo_turno"}]),
 m("avaliacao_tatica", "Avaliação Tática", 135, "no_teste",
   "Soma o Dado de Superioridade a um teste de Inteligência (História ou Investigação) ou de Sabedoria (Intuição).",
   [{"tipo": "modificador", "alvo": "teste_de_atributo", "valor": [DS], "empilha": "soma"}],
   testes_aplicaveis=[{"atributo": "INT", "pericias": ["historia", "investigacao"]},
                      {"atributo": "SAB", "pericias": ["intuicao"]}]),
 m("contra_ataque", "Contra-ataque", 135, "reacao",
   "Quando uma criatura erra um ataque corpo a corpo contra você, Reação para atacá-la com arma ou Ataque Desarmado; acertando, soma o Dado de Superioridade ao dano.",
   [{"tipo": "conceder_ataque", "quantidade": ["1"], "custo": "reacao",
     "gatilho": "criatura_erra_ataque_corpo_a_corpo_contra_voce"},
    {"tipo": "dano", "formula_dado": DS, "modo": "dano_adicional", "condicao": {"todas": ["acerto"]}}]),
 m("desarme", "Desarme", 135, "no_acerto",
   "Soma o Dado de Superioridade ao dano; o alvo faz salvaguarda de Força ou solta um objeto à sua escolha, que cai no espaço dele.",
   [{"tipo": "dano", "formula_dado": DS, "modo": "dano_adicional", "tipo_dano": "mesmo_do_ataque"},
    {"tipo": "efeito_narrativo", "chave": "desarmar", "salvaguarda": {"atributo": "FOR", "cd": CD},
     "texto": "Falhando, o alvo solta um objeto à sua escolha que esteja segurando; o objeto cai no espaço dele."}]),
 m("emboscada", "Emboscada", 135, "no_teste",
   "Soma o Dado de Superioridade a um teste de Destreza (Furtividade) ou à jogada de Iniciativa, salvo se você estiver Incapacitado.",
   [{"tipo": "modificador", "alvo": "teste_de_atributo", "valor": [DS], "empilha": "soma",
     "condicao": {"nao": "condicao:incapacitado"}},
    {"tipo": "modificador", "alvo": "iniciativa", "valor": [DS], "empilha": "soma",
     "condicao": {"nao": "condicao:incapacitado"}}],
   testes_aplicaveis=[{"atributo": "DES", "pericias": ["furtividade"]}]),
 m("encontrao", "Encontrão", 135, "no_acerto",
   "Soma o Dado de Superioridade ao dano; se o alvo for Grande ou menor, salvaguarda de Força ou é empurrado até 4,5 m para longe.",
   [{"tipo": "dano", "formula_dado": DS, "modo": "dano_adicional", "tipo_dano": "mesmo_do_ataque"},
    {"tipo": "efeito_narrativo", "chave": "empurrao", "salvaguarda": {"atributo": "FOR", "cd": CD},
     "texto": "Alvo Grande ou menor que falhar é empurrado até 4,5 metros para longe de você."}]),
 m("finta", "Finta", 135, "acao_bonus",
   "Ação Bônus escolhendo uma criatura a até 1,5 m: Vantagem no seu próximo ataque contra ela neste turno; acertando, soma o Dado de Superioridade ao dano.",
   [{"tipo": "vantagem", "alvo": "jogada_de_ataque", "modo": "vantagem", "duracao": "neste_turno"},
    {"tipo": "dano", "formula_dado": DS, "modo": "dano_adicional", "condicao": {"todas": ["acerto"]}}]),
 m("gato_por_lebre", "Gato Por Lebre", 135, "movimento",
   "Troca de lugar com uma criatura voluntária e não Incapacitada a até 1,5 m, gastando ao menos 1,5 m de movimento e sem provocar Ataques de Oportunidade. Até o início do seu próximo turno, você ou ela (à sua escolha) ganha bônus de CA igual ao resultado do dado.",
   [{"tipo": "efeito_narrativo", "chave": "troca_de_lugar",
     "texto": "Troca de posição com a criatura; o movimento não provoca Ataques de Oportunidade."},
    {"tipo": "modificador", "alvo": "ca_total", "valor": [DS], "empilha": "soma",
     "beneficiario": "voce_ou_a_criatura", "duracao": "ate_inicio_do_seu_proximo_turno"}],
   revisao={"status": "duvida", "notas": "Na extração do PDF o parágrafo 'Jogue o Dado de Superioridade. Até o início do seu próximo turno, você ou a outra criatura (à sua escolha) adquire um bônus de CA igual ao número do resultado' aparece solto entre 'Gato Por Lebre' e 'Golpe do Comandante', por causa da quebra de coluna. Li como continuação de Gato Por Lebre (é o que faz sentido mecânico e alfabético). Confirmar no livro impresso."}),
 m("golpe_do_comandante", "Golpe do Comandante", 135, "substitui_ataque",
   "Na ação Atacar, troca um ataque por instruir um aliado que possa vê-lo ou ouvi-lo: ele usa a Reação dele para atacar, somando o Dado de Superioridade ao dano em caso de acerto.",
   [{"tipo": "conceder_ataque", "quantidade": ["1"], "beneficiario": "aliado", "custo": "reacao_do_aliado"},
    {"tipo": "dano", "formula_dado": DS, "modo": "dano_adicional", "beneficiario": "aliado",
     "condicao": {"todas": ["acerto"]}}]),
 m("manobrar", "Manobrar", 135, "no_acerto",
   "Soma o Dado de Superioridade ao dano e escolhe um aliado que possa vê-lo ou ouvi-lo: ele usa a Reação dele para mover metade do Deslocamento sem provocar Ataque de Oportunidade do alvo do seu ataque.",
   [{"tipo": "dano", "formula_dado": DS, "modo": "dano_adicional", "tipo_dano": "mesmo_do_ataque"},
    {"tipo": "efeito_narrativo", "chave": "reposicionar_aliado",
     "texto": "O aliado usa a Reação dele para mover até metade do Deslocamento sem provocar Ataque de Oportunidade do alvo do seu ataque."}]),
 m("movimentacao_evasiva", "Movimentação Evasiva", 135, "acao_bonus",
   "Ação Bônus para executar Desengajar e somar o resultado do dado à sua CA até o início do seu próximo turno.",
   [{"tipo": "conceder_acao", "id": "manobra_desengajar", "custo": "acao_bonus", "acoes": ["desengajar"]},
    {"tipo": "modificador", "alvo": "ca_total", "valor": [DS], "empilha": "soma",
     "duracao": "ate_inicio_do_seu_proximo_turno"}]),
 m("presenca_de_autoridade", "Presença de Autoridade", 135, "no_teste",
   "Soma o Dado de Superioridade a um teste de Carisma (Atuação, Intimidação ou Persuasão).",
   [{"tipo": "modificador", "alvo": "teste_de_atributo", "valor": [DS], "empilha": "soma"}],
   testes_aplicaveis=[{"atributo": "CAR", "pericias": ["atuacao", "intimidacao", "persuasao"]}]),
 m("prostrar", "Prostrar", 135, "no_acerto",
   "Soma o Dado de Superioridade ao dano; se o alvo for Grande ou menor, salvaguarda de Força ou fica Caído.",
   [{"tipo": "dano", "formula_dado": DS, "modo": "dano_adicional", "tipo_dano": "mesmo_do_ataque"},
    {"tipo": "conceder_condicao", "condicao_id": "caido", "beneficiario": "alvo",
     "salvaguarda": {"atributo": "FOR", "cd": CD}, "condicao": {"todas": ["alvo_grande_ou_menor"]}}]),
 m("recuperar_energia", "Recuperar Energia", 135, "acao_bonus",
   "Ação Bônus: um aliado a até 9 m que possa vê-lo ou ouvi-lo ganha PV temporários iguais ao Dado de Superioridade mais metade do seu nível de Guerreiro (arredondado para baixo).",
   [{"tipo": "pontos_de_vida_temporarios", "beneficiario": "aliado",
     "formula": [DS, {"op": "div_arred_baixo", "args": ["nivel_classe:guerreiro", "2"]}]}]),
]
json.dump({"catalogo": "manobras", "nome": "Manobras (Mestre da Batalha)",
           "fonte": f(134), "total": len(M),
           "nota": "Cada manobra gasta um Dado de Superioridade. CD das que exigem salvaguarda: 8 + mod. de Força OU Destreza (à sua escolha) + Bônus de Proficiência (p. 133).",
           "cd_das_manobras": CD, "itens": M},
          open(os.path.join(D, 'catalogos/manobras.json'), 'w', encoding='utf-8'),
          ensure_ascii=False, indent=2)
print('manobras:', len(M))
